### ISSUE TITLE
NameError: global name 'comment_stream_urls' is not defined

### ISSUE THREAD

**Issue by tek0011** [tek0011/reddit_info_bot#43]
[root@redditbots redditbot]# python2.7 info_bot_nsfw.py
Adding Rarchives links to blacklist.
/usr/local/lib/python2.7/site-packages/praw/decorators.py:74: DeprecationWarning: reddit intends to disable password-based authentication of API clients sometime in the near future. As a result this method will be removed in a future major version of PRAW.

For more information please see:

* Original reddit deprecation notice: https://www.reddit.com/comments/2ujhkr/

* Updated delayed deprecation notice: https://www.reddit.com/comments/37e2mv/

Pass ``disable_warning=True`` to ``login`` to disable this warning.
  warn(msg, DeprecationWarning)
POST: https://api.reddit.com/api/login/.json
data: {u'passwd': u'J179n317s!1', u'user': u'info_bot_nsfw'}
status: 200
POST: https://api.reddit.com/api/login/.json
data: {u'passwd': u'j159n357s', u'user': u'info_bot_parser'}
status: 200
Traceback (most recent call last):
  File "info_bot_nsfw.py", line 588, in <module>
    main()
  File "info_bot_nsfw.py", line 554, in main
    for stream in comment_stream_urls: #uses separate comment streams for large subreddit list due to URL length limit
NameError: global name 'comment_stream_urls' is not defined

**Comment by nyov** [comment]
Well that's quite embarassing; how did I manage to ignore those globals...

I hope #44 works as a quick fix. I'll be moving it over to OAuth asap, when time is back,
but for now I disabled the warning and haven't had any issues with praw 3.2.0
(Though the bot didn't get to comment on anything in my test, so that is untested.)
I didn't get the error in #34 though. Is that still a problem?
