### ISSUE TITLE
versioning scheme

### ISSUE THREAD

**Issue by nyov** [tek0011/reddit_info_bot#78]
What's the versioning scheme we should use for the package?
I wouldn't want to disregard the previous efforts, so starting at `0.1` is maybe wrong, but some kind of version numbers would be good I think.

**Comment by nyov** [comment]
I think maybe starting at 1.0, or 2.0. Or to be completely unbiased, something like `2015.10` (year.month) might work?

**Comment by tek0011** [comment]
forgot about answering this.  I have just been versioning as I see fit by setting it in the config.  
basically for every bug fix I do a minor (3.1.0, 3.2.0, 3.3.0, etc)
for quick fixes or small enhancements I have been doing (3.1.0, 3.1.1, 3.1.2, etc)

For large releases with a ton of changes I will do the major version.

However, I like your idea on year.month - honestly, I dont really care, Im mostly doing it because praw/reddit ask you to.  They will ban/unban or do things with bots based on versioning.  The thing is I have no idea what they do, so I havent really cared lol.

Anything that is automated would be nice.  Bot Version = "%m_%d_%R" - or anything that would automate it.

**Comment by nyov** [comment]
Okay, I have no real preference either.
So I would just take `year.month[.minor]` for the package version.
The bot's version announced to reddit can be different from that, by setting `BOT_VERSION`, but would default to the package version if not set. That should take care of automating it (as long as a version is tagged in git once in a while).
I could further automate to pull in the git commit, that would look like `2015.10.a91249b` (meaning commit [a91249b](https://github.com/tek0011/reddit_info_bot/tree/a91249b)) then. As that is always unique, it wouldn't be necessary then to manually set a minor number on every small update.

**Comment by tek0011** [comment]
You get the pal pal for this latest milestone?

And yes, any way you want to setup the versioning works for me.  Date would
be cool, because I want to plug in the version info into the footer message.

On Mon, Oct 26, 2015 at 4:35 PM, nyov <notifications@github.com> wrote:

> Okay, I have no real preference either.
> So I would just take year.month[.minor] for the package version.
> The bot's version announced to reddit can be different from that, by
> setting BOT_VERSION, but would default to the package version if not set.
> That should take care of automating it (as long as a version is tagged in
> git once in a while).
> I could further automate to pull in the git commit, that would look like
> 2015.10.a91249b (meaning commit a91249b
> <https://github.com/tek0011/reddit_info_bot/tree/a91249b>) then. As that
> is always unique, it wouldn't be necessary then to manually set a minor
> number on every small update.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tek0011/reddit_info_bot/issues/78#issuecomment-151291506>
> .
>



-- 
Jeff

**Comment by nyov** [comment]
Yay, many thanks.

But dang, pep 440 says I can't really use the git hash for numbering (as if I care), but then it would become something like `2015.10.dev17` instead (where 17 is from `git describe` and says 17 new commits since last release. Not very useful, but it's an increasing number :).

**Comment by tek0011** [comment]
That works.  For all I care we could do *2015.10.somerandom* number.  lol

On Tue, Oct 27, 2015 at 8:13 AM, nyov <notifications@github.com> wrote:

> Yay, many thanks.
>
> But dang, pep 440 says I can't really use the git hash for numbering (as
> if I care), but then it would become something like 2015.10.dev17 instead
> (where 17 is from git describe and says 17 new commits since last
> release. Not very useful, but it's an increasing number :).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tek0011/reddit_info_bot/issues/78#issuecomment-151490544>
> .
>



-- 
Jeff
